/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Logger } from "./tests/components/logger";
export { Logger } from "./tests/components/logger";
export namespace Components {
    interface AppExample {
    }
    interface ConsumeExample {
        "getLogger": () => Promise<Logger | undefined>;
    }
    interface ProvideExample {
        /**
          * @default new Logger()
         */
        "logger": Logger;
        "section": string;
    }
}
declare global {
    interface HTMLAppExampleElement extends Components.AppExample, HTMLStencilElement {
    }
    var HTMLAppExampleElement: {
        prototype: HTMLAppExampleElement;
        new (): HTMLAppExampleElement;
    };
    interface HTMLConsumeExampleElement extends Components.ConsumeExample, HTMLStencilElement {
    }
    var HTMLConsumeExampleElement: {
        prototype: HTMLConsumeExampleElement;
        new (): HTMLConsumeExampleElement;
    };
    interface HTMLProvideExampleElement extends Components.ProvideExample, HTMLStencilElement {
    }
    var HTMLProvideExampleElement: {
        prototype: HTMLProvideExampleElement;
        new (): HTMLProvideExampleElement;
    };
    interface HTMLElementTagNameMap {
        "app-example": HTMLAppExampleElement;
        "consume-example": HTMLConsumeExampleElement;
        "provide-example": HTMLProvideExampleElement;
    }
}
declare namespace LocalJSX {
    interface AppExample {
    }
    interface ConsumeExample {
    }
    interface ProvideExample {
        /**
          * @default new Logger()
         */
        "logger"?: Logger;
        "section"?: string;
    }

    interface ProvideExampleAttributes {
        "section": string;
    }

    interface IntrinsicElements {
        "app-example": AppExample;
        "consume-example": ConsumeExample;
        "provide-example": Omit<ProvideExample, keyof ProvideExampleAttributes> & { [K in keyof ProvideExample & keyof ProvideExampleAttributes]?: ProvideExample[K] } & { [K in keyof ProvideExample & keyof ProvideExampleAttributes as `attr:${K}`]?: ProvideExampleAttributes[K] } & { [K in keyof ProvideExample & keyof ProvideExampleAttributes as `prop:${K}`]?: ProvideExample[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-example": LocalJSX.IntrinsicElements["app-example"] & JSXBase.HTMLAttributes<HTMLAppExampleElement>;
            "consume-example": LocalJSX.IntrinsicElements["consume-example"] & JSXBase.HTMLAttributes<HTMLConsumeExampleElement>;
            "provide-example": LocalJSX.IntrinsicElements["provide-example"] & JSXBase.HTMLAttributes<HTMLProvideExampleElement>;
        }
    }
}
